metadata:
  name: hostpath-exec-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: container
            volumeMounts:
            - mountPath: /host
              name: noderoot
          volumes:
          - name: noderoot
            hostPath:
              path: /
