metadata:
  name: hostpath-exec-job
spec:
  template:
    spec:
      containers:
      - name: container
        volumeMounts:
        - mountPath: /host
          name: noderoot
      volumes:
      - name: noderoot
        hostPath:
          path: /