metadata:
  name: priv-exec-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: container
            securityContext:
              privileged: true
